application: sparkleword
version: 8
runtime: python27
api_version: 1
threadsafe: yes

builtins:
#- datastore_admin: on
- remote_api: on

libraries:
- name: django
  version: latest

handlers:

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

# mapping to the Django admin site's static files.
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

# helper to get logged out of your app engine session
#- url: /logout
#script: util/logout.py

# cronjob.
- url: /cron/.*
  script: djangoappengine.main.application
  login: admin

# miscellaneous static files.
- url: /static
  static_dir: static
  expiration: '0'

# main site.
- url: /.*
  script: djangoappengine.main.application
