# This file will be post-processed to generate the actual app.yaml use when deploying to 
# Google App Engine.
application: sparkleword
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

# mapping to the Django admin site's static files.
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

# helper to get logged out of your app engine session
- url: /logout
  script: util/logout.py

# cronjob.
- url: /cron/.*
  script: djangoappengine/main/main.py
  login: admin

# main site.
- url: /.*
  script: djangoappengine/main/main.py
